version: '3'
services:
  backend:
    build:
      context: ./backend   # Correct the path to point to your backend directory
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
    depends_on:
      - mongo
    networks:
      - hospital-network

  mongo:
    image: mongo
    volumes:
      - ./data/db:/data/db
    networks:
      - hospital-network

networks:
  hospital-network:
    driver: bridge
